repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.5   # pick a stable version of ruff
    hooks:
      - id: ruff
        args: [--fix]   # auto-fix lint issues when possible
      - id: ruff-format # for formatting (instead of black, if you prefer ruff-only)

  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.10.0
    hooks:
      - id: mypy

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: end-of-file-fixer
