"""initial schema

Revision ID: 1bf6e0e2db42
Revises: feda7b23dfeb
Create Date: 2025-09-10 14:03:47.220881

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1bf6e0e2db42"
down_revision: Union[str, Sequence[str], None] = "feda7b23dfeb"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
